services:
  web:
    image: 'gitlab/gitlab-ee:latest'
    ports:
      - '8084:80'
      - '4430:443'
      - '2200:22'
    volumes:
      - '$GITLAB_HOME/config:/etc/gitlab'
      - '$GITLAB_HOME/logs:/var/log/gitlab'
      - '$GITLAB_HOME/data:/var/opt/gitlab'
    networks:
      - gitlab-ee

  runner:
    image: 'gitlab/gitlab-runner:latest'
    volumes:
      - '/srv/gitlab-runner/config:/home/shitajimado/gitlab'
      - '/var/run/docker.sock:/var/run/docker.sock'
    networks:
      - gitlab-ee

networks:
  gitlab-ee:
    name: 'gitlab-hse'
    driver: 'bridge'
