variables:
  NPROC: 8

image: ubuntu:latest

stages:
  - build
  - test
  - package

x64.l.build:
  stage: build
  script:
    - apt-get update
    - DEBIAN_FRONTEND=noninteractive apt-get install -yq  build-essential scons pkg-config libx11-dev libxcursor-dev libxinerama-dev
      libgl1-mesa-dev libglu-dev libasound2-dev libpulse-dev libudev-dev libxi-dev libxrandr-dev yasm
    - scons -j8 platform=linuxbsd bits=64 target=release_debug tests=yes
  artifacts:
    paths:
      - bin/

x64.l.test:
  stage: test
  script:
    - ./bin/godot.linuxbsd.opt.tools.64  --test

x64.l.package:
  stage: package
  script:
    - mkdir package
    - export PACKAGE_PATH=$(pwd)/package
    - cd bin
    - tar cf godot.tar.gz $PACKAGE_PATH --gzip
  artifacts:
    paths:
      - $PACKAGE_PATH/godot.tar.gz
